GO

CREATE TABLE DIM_TIEMPO(

COD_TIEMPO DATE NOT NULL,

NUM_ANHO INT NOT NULL,

NUM_TRIMESTRE INT NOT NULL,

NUM_MES INT NOT NULL,

DESC_MES NVARCHAR(50) NOT NULL,

NUM_DIA INT NOT NULL,

DESC_DIA NVARCHAR(50) NOT NULL,

FEC_PROCESAMIENTO DATETIME NOT NULL,

CONSTRAINT PK_DIM_TIEMPO PRIMARY KEY (COD_TIEMPO));

GO

ALTER TABLE DIM_TIEMPO ADD DEFAULT (GETDATE()) FOR FEC_PROCESAMIENTO

GO